name: Cypress Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout, install packages, cache
        uses: actions/checkout@v1
      - name: Run one example test
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/examples/actions.spec.js
