name: Cypress Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress:
    runs-on: ubuntu-latest
    name: Cypress Tests
    steps:
      - name: Checkout, install packages, cache
        uses: actions/checkout@v1
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:8080"
          test: yarn test:sections
