name: Cypress Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    name: Cypress on Node.js v${{ matrix.node-version }}

    steps:
      - name: Checkout
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          group: Tests on Node.js v${{ matrix.node-version }}
          build: yarn build
          start: yarn test:start
          wait-on: "http://localhost:8080"
          wait-on-timeout: 30
          spec: "cypress/integration/sections/**"
