name: Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Cypress on Node v12

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn test:start
          wait-on: "http://localhost:8080"
          wait-on-timeout: 30
          spec: "cypress/integration/sections/**"
